# Generated by Django 5.2.4 on 2025-07-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('asked_in', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Logical', 'Logical'), ('Mathematical', 'Mathematical'), ('Arrangement', 'Arrangement'), ('Shape', 'Shape'), ('Other', 'Other')], max_length=50)),
                ('solved', models.BooleanField(default=False)),  # type: ignore
            ],
        ),
    ]
